name: push-build-release
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on: 

  push:
    tags:
      - 'v*'
  pull_request:
    branches: [develop]
jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    uses: EddyTheCo/Common/.github/workflows/build-test-install.yml@v0.1.2
    permissions:
      contents: write
    with:
      os: ${{ matrix.os }}
      cmakeArgs: ' -DUSE_THREADS=ON -DQTDEPLOY=ON'  
      qtModules: 'qtwebsockets qtshadertools qtmultimedia'
      qtVersion: '6.6.0'  
      test: false
  build-android:
    strategy:
      matrix:
        qtArch: ['android_arm64_v8a','android_armv7']  

    uses: EddyTheCo/Common/.github/workflows/build-android.yml@v0.1.2
    with:
      qtModules: 'qtwebsockets qtshadertools qtmultimedia'
      qtTarget: 'nftminter'
      qtVersion: '6.6.0'  
      cmakeArgs: ' -DUSE_THREADS=ON '  
      qtArch: ${{ matrix.qtArch }}  
    secrets:
      QT_ANDROID_KEYSTORE_STORE_PASS:  ${{ secrets.QT_ANDROID_KEYSTORE_STORE_PASS }}
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_test_package,build-android]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v4
    
      - uses: actions/download-artifact@v4
        with:
           path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*       
