name: push-build-release
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on: 

  push:
    tags:
      - 'v*'
  pull_request:
    branches: [develop]
jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        sharedLib: [true]
        useThread: [true,false]

    uses: EddyTheCo/Common/.github/workflows/build-test-install.yml@main
    permissions:
      contents: write
    with:
      os: ${{ matrix.os }}
      sharedLib: ${{ matrix.sharedLib }}
      useThread: ${{ matrix.useThread }}
      qtModules: 'qtwebsockets qtshadertools qtmultimedia'
      qtVersion: '6.6.0'  
      test: false
    secrets:
      NODE_JWT: ${{ secrets.NODE_JWT }}
  build-android:
    strategy:
      matrix:
        useThread: [true,false]

    uses: EddyTheCo/Common/.github/workflows/build-android.yml@main
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtTarget: 'nftminter'
      qtVersion: '6.6.0'  
      useThread: ${{ matrix.useThread }}
    secrets:
      QT_ANDROID_KEYSTORE_STORE_PASS:  ${{ secrets.QT_ANDROID_KEYSTORE_STORE_PASS }}
      NODE_JWT: ${{ secrets.NODE_JWT }}
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_test_package,build-android]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v3
    
      - uses: actions/download-artifact@v3
        with:
           path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*       
