name: build-wasm
run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }} 
on:
  pull_request_target:
    types: [closed]
    branches: [main]
jobs:
  build-html:
    uses: EddyTheCo/Common/.github/workflows/build-wasm.yml@v0.1.1
    if: ${{ (github.event.pull_request.merged == true) && (startsWith(github.base_ref, 'main')) }}  
    permissions:
      pages: write
      id-token: write
    with:
      qtModules: 'qtwebsockets qtshadertools'
      qtVersion: '6.6.0'
      emsdkVersion: '3.1.37'
    secrets:
      NODE_JWT: ${{ secrets.NODE_JWT }}
